class AddColumnsToDownwardArrow < ActiveRecord::Migration[5.1]
  def change
    add_column :downward_arrows, :autothought2, :string
    add_column :downward_arrows, :distortion2, :string
    add_column :downward_arrows, :response2, :string
    add_column :downward_arrows, :autothought3, :string
    add_column :downward_arrows, :distortion3, :string
    add_column :downward_arrows, :response3, :string
    add_column :downward_arrows, :autothought4, :string
    add_column :downward_arrows, :distortion4, :string
    add_column :downward_arrows, :response4, :string
    add_column :downward_arrows, :autothought5, :string
    add_column :downward_arrows, :distortion5, :string
    add_column :downward_arrows, :response5, :string
    add_column :downward_arrows, :autothought6, :string
    add_column :downward_arrows, :distortion6, :string
    add_column :downward_arrows, :response6, :string
    add_column :downward_arrows, :autothought7, :string
    add_column :downward_arrows, :distortion7, :string
    add_column :downward_arrows, :response7, :string
    add_column :downward_arrows, :autothought8, :string
    add_column :downward_arrows, :distortion8, :string
    add_column :downward_arrows, :response8, :string
    add_column :downward_arrows, :autothought9, :string
    add_column :downward_arrows, :distortion9, :string
    add_column :downward_arrows, :response9, :string
    add_column :downward_arrows, :autothought10, :string
    add_column :downward_arrows, :distortion10, :string
    add_column :downward_arrows, :response10, :string
    add_column :downward_arrows, :autothought11, :string
    add_column :downward_arrows, :distortion11, :string
    add_column :downward_arrows, :response11, :string
    add_column :downward_arrows, :autothought12, :string
    add_column :downward_arrows, :distortion12, :string
    add_column :downward_arrows, :response12, :string
    add_column :downward_arrows, :autothought13, :string
    add_column :downward_arrows, :distortion13, :string
    add_column :downward_arrows, :response13, :string
    add_column :downward_arrows, :autothought14, :string
    add_column :downward_arrows, :distortion14, :string
    add_column :downward_arrows, :response14, :string
    add_column :downward_arrows, :autothought15, :string
    add_column :downward_arrows, :distortion15, :string
    add_column :downward_arrows, :response15, :string
    add_column :downward_arrows, :autothought16, :string
    add_column :downward_arrows, :distortion16, :string
    add_column :downward_arrows, :response16, :string
    add_column :downward_arrows, :autothought17, :string
    add_column :downward_arrows, :distortion17, :string
    add_column :downward_arrows, :response17, :string
    add_column :downward_arrows, :autothought18, :string
    add_column :downward_arrows, :distortion18, :string
    add_column :downward_arrows, :response18, :string
    add_column :downward_arrows, :autothought19, :string
    add_column :downward_arrows, :distortion19, :string
    add_column :downward_arrows, :response19, :string
    add_column :downward_arrows, :autothought20, :string
    add_column :downward_arrows, :distortion20, :string
    add_column :downward_arrows, :response20, :string
  end
end
